# Generating Random Numbers Using NumPy


In [3]:
# Step 1: Import NumPy
import numpy as np

## 1. Generate Random Floats Between 0 and 1  
`np.random.rand()` generates a random float number between 0 and 1 (exclusive)

In [34]:
# Generate one random number between 0 and 1
random_number = np.random.rand()
print(random_number)

# 1D array of random numbers between 0 and 1
array_of_randoms_1d = np.random.rand(5)
print(array_of_randoms_1d)

# Generate a 3x2 matrix of random numbers between 0 and 1
array_of_randoms = np.random.rand(3, 2)
print(array_of_randoms)

0.9656320330745594
[0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
[[0.12203823 0.49517691]
 [0.03438852 0.9093204 ]
 [0.25877998 0.66252228]]


## 2. Generate Random Integers  
`np.random.randint(low, high)` gives a random integer between low (inclusive) and high (exclusive)

In [18]:
# This will generate a random integer in the range [1, 10)
random_integer = np.random.randint(1, 10)
print(random_integer)

# This will generate a 3x2 matrix of random integers in the range [1, 10)
random_integers = np.random.randint(1, 10, size=(3, 2))
print(random_integers)

9
[[4 9]
 [3 3]
 [3 1]]


## 3. Generate Random Numbers from a Standard Normal Distribution  
`np.random.randn()` generates numbers from a standard normal distribution (mean = 0, std = 1)


In [37]:
normal_numbers = np.random.randn(5)
print(normal_numbers)

# This will generate a 2x3 matrix of random numbers from a normal distribution with mean 0 and standard deviation 1
normal_matrix = np.random.randn(2, 3)
print(normal_matrix)

[ 0.31890218  0.27904129  1.01051528 -0.58087813 -0.52516981]
[[-0.57138017 -0.92408284 -2.61254901]
 [ 0.95036968  0.81644508 -1.523876  ]]


## 4. Generate Random Numbers from a Custom Normal Distribution  
`loc` is the mean, `scale` is the standard deviation, and `size` is how many numbers to generate.

In [23]:
# This will generate a 4 random numbers from a normal distribution with mean 50 and standard deviation 5

normal_custom = np.random.normal(loc=50, scale=5, size=4)
print(normal_custom)

[51.67655024 52.69899461 50.57169451 48.88619904]


## 5. Generate Random Numbers from a Uniform Distribution  
This gives 3 float numbers between 5 and 10.

In [5]:
uniform_numbers = np.random.uniform(low=5, high=10, size=3)
print(uniform_numbers)

[8.35303534 5.69666177 9.93681312]


## 6. Randomly Pick Elements from a List

In [28]:
# Randomly selects 3 elements from the list.
choices = np.random.choice([10, 20, 20, 20, 30, 40, 40, 40, 50], size=3)
print(choices)

# You can also set replace=False to avoid duplicates
unique_choices = np.random.choice([10, 20, 30, 40, 50], size=3, replace=False)
print(unique_choices)

[20 40 20]
[40 50 30]


## 7. Shuffle an Array  
This shuffles the array in place (changes the original array).

In [29]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[4 5 1 3 2]


## Set a Seed for Reproducibility
This fixes the sequence of random numbers so they are repeatable.

In [35]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
